development:
  adapter: postgresql
  encoding: unicode
  database: api_ecommerce
  pool: 5
  username: postgres
  password: root
  host: localhost
  # port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: api_ecommerce_teste
  pool: 5
  username: postgres
  password: root
  host: localhost
  # port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: api_ecommerce_production
  pool: 5
  username: postgres
  password: root
  host: localhost
  # port: 5432